// Generated by Wrangler
// After adding bindings to `wrangler.json`, regenerate this interface via `npm run cf-typegen`
interface Env {
    SUPABASE_URL: string;
    SUPABASE_KEY: string;
    STRIPE_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    ENVIRONMENT: string;
    RAID_REVIEW: R2Bucket;
}
