export const LOCATIONS: { [key: string]: string } = {
    "bigmap": "Customs",
    "Sandbox": "Ground Zero",
    "develop": "Ground Zero",
    "factory4_day": "Factory",
    "factory4_night": "Factory",
    "hideout": "Hideout",
    "Interchange": "Interchange",
    "laboratory": "Laboratory",
    "Lighthouse": "Lighthouse",
    "privatearea": "Private Area",
    "RezervBase": "Reserve",
    "Shoreline": "Shoreline",
    "suburbs": "Suburbs",
    "TarkovStreets": "Streets",
    "terminal": "Terminal",
    "town": "Town",
    "Woods": "Woods",
    "base": "Base"
};